FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openssh-server \
    python3 \
    python3-pip \
    sudo \
    iproute2 \
    net-tools \
    vim \
    curl \
    wget && \
    apt-get clean

RUN mkdir /var/run/sshd

RUN useradd -m -s /bin/bash redisadmin && \
    echo "redisadmin ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

COPY redisadmin.pub /tmp/redisadmin.pub

RUN mkdir -p /home/redisadmin/.ssh && \
    cat /tmp/redisadmin.pub > /home/redisadmin/.ssh/authorized_keys && \
    chown -R redisadmin:redisadmin /home/redisadmin/.ssh && \
    chmod 700 /home/redisadmin/.ssh && \
    chmod 600 /home/redisadmin/.ssh/authorized_keys

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
