[redis]
redis-node-1 ansible_host=127.0.0.1 ansible_port=2201
redis-node-2 ansible_host=127.0.0.1 ansible_port=2202
redis-node-3 ansible_host=127.0.0.1 ansible_port=2203
redis-node-4 ansible_host=127.0.0.1 ansible_port=2204
redis-node-5 ansible_host=127.0.0.1 ansible_port=2205
redis-node-6 ansible_host=127.0.0.1 ansible_port=2206

[redis:vars]
ansible_user=redisadmin
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
